# Default values for nginx
serviceAccount:
  create: false
nginx:
  enabled: false
  service:
    type: ClusterIP
  ingress:
    enabled: false
    hostname: ''
    path: '/*'
    annotations: {}
    extraHosts: []
    extraPaths: []
    extraTls: []
    secrets: []
#   serverBlock: |-
#     server {
#       listen 80;
#       server_name www.example.com example.com;
#       location /blog {
#          proxy_pass http://node1.com:8000/wordpress/;
#       }
#     }
