# Default values for nginx
serviceAccount:
  create: false
nginx:
  enabled: false
  service:
    type: ClusterIP
  ingress:
    enabled: false
    hostname: ''
    path: '/*'
    annotations: {}
    extraHosts: []
    extraPaths: []
    extraTls: []
    secrets: []
  serverBlock: |-
    server {
      listen 0.0.0.0:8080;
      location / {
        return 200 "hello!";
      }
    }
