apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name:  "argo-workflow-dev"
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: "https://kubernetes.default.svc"
    namespace: dev
  project: "default"
  source:
    repoURL: https://github.com/jrhoward/helm-umbrella-argocd/simple-wrapper-demo/
    chart: simple-wrapper-demo
    targetRevision: HEAD
    helm:
      releaseName: dev
      version: v3
      valueFiles:
        - config/env/tennant-1/dev.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true