apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name:  "argo-workflow-test"
  namespace: argo-cd
spec:
  destination:
    server: "https://kubernetes.default.svc"
    namespace: test
  project: "default"
  source:
    repoURL: https://github.com/jrhoward/helm-umbrella-argocd.git/simple-wrapper-demo/
    chart: simple-wrapper-demo
    targetRevision: HEAD
    helm:
      releaseName: test
      version: v3
      valueFiles:
        - config/env/tennant-1/test.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
